# Site settings
title: 'Cheat-sheets.tk'
email: #jordihv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My notes on Web development, Vim, Git, Linux.
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cheat-sheets.tk" # the base hostname & protocol for your site
permalink: none
# twitter_username: jekyllrb
# github_username: johgh
    
    
# Build settings
# markdown: kramdown

# kramdown:
#     input: GFM
gems:
- jekyll-sitemap
- jekyll_github_sample
- jekyll-last-modified-at

include:
- .nojekyll

destination: source

minItemsToShowToc: 2
showToggleButton: true
