# docker run --rm -it \
# --volume="$PWD:/srv/jekyll" \
# --volume="$PWD/vendor/bundle:/usr/local/bundle" \
# -p 4000:4000 jekyll/jekyll:3.8 \
# jekyll serve
version: '3'
services:
  jekyll-serve:
    image: jekyll/jekyll:3.8
    volumes:
      - ".:/srv/jekyll"
    ports:
      - 4000:4000
    command: 'jekyll serve'

