name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Jekyll site.
      uses: fabacab/jekyll-builder-for-github-pages-action@v1 # Or whatever "@ref" you want.
